CCUBE-1512-1
LifeSG/web-form-builder pull request #111
Opened 2024-08-13 02:28 UTC by adenteo

**Changes**
- Create common functions and helpers for generate schema logic.
- Create separate schema generators for each element type.
- Add test cases for each element schema generator.
- Edit test cases for translator.
- Extract validationType yup schema.
- Remove unused element types.
-  Rename functions and file in generator to start with generate.
- Add base schema test cases.

**Additional information**
-   You may refer to this [ticket](https://jira.ship.gov.sg/browse/CCUBE-1512)

2024-08-14 02:36 UTC, weili-govtech requested changes

2024-08-14 02:36 UTC, weili-govtech commented on src/schemas/text-based-fields.ts
> +        })
is it necessary to convert to undefined? required validation works for empty string too

2024-08-14 02:36 UTC, weili-govtech commented on src/translator/generate/index.ts
do barrel export for `elements/` only because only they are used outside the folder

when importing within the same folder, avoid import via barrel exports because it may cause circular imports

2024-08-14 02:48 UTC, adenteo commented on src/schemas/text-based-fields.ts
> +        })
It seems to be necessary. Without it, the `oneOf` validation would trigger and return an error message.

2024-08-15 01:20 UTC, weili-govtech requested changes

2024-08-15 01:20 UTC, weili-govtech commented on src/translator/generate/elements/numeric/numeric-schema-generator.ts
> +import { ISchemaValidation } from "../..";
```suggestion
import { ISchemaValidation } from "../../types";
```

2024-08-15 01:20 UTC, weili-govtech commented on src/schemas/text-based-fields.ts
> +        })
looks like `oneOf` takes higher precedence over `required`, there are other workarounds but I think this is sufficient too so I am resolving this issue

2024-08-16 01:24 UTC, weili-govtech commented
need to fix the import in `validation-generators.ts` too

2024-08-16 09:53 UTC, weili-govtech approved these changes

2024-08-16 09:53 UTC, merged