[CCUBE-1220][SR] Added a new test for add elements panel
LifeSG/web-form-builder pull request #36
Opened 2024-04-18 04:58 UTC by ShIrInRuTh

**Changes**
- Added a new test for rendering of element selector cards based on categories in the add elements panel

**Additional information**
-   You may refer to this [CCUBE-1220](https://jira.ship.gov.sg/browse/CCUBE-1220)

2024-04-18 06:38 UTC, keithtxw submitted a review, later dismissed

2024-04-18 06:38 UTC, keithtxw commented on tests/components/add-elements-panel/add-elements-panel.spec.tsx
> +    });
Able to click on one of the element card and ensure the `addElement` is being triggered

2024-04-19 10:01 UTC, weili-govtech requested changes

2024-04-19 10:01 UTC, weili-govtech commented on tests/components/add-elements-panel/add-elements-panel.spec.tsx
> +                });
why check via `getAllByText` instead of `getByText`?
`getByText` will throw an error if it gets more than one match

```suggestion
                category.elementTypes.forEach((elementType) => {
                    expect(
                        screen.getByText(ELEMENT_BUTTON_LABELS[elementType])
                    ).toBeInTheDocument();
                });
```

2024-04-23 03:03 UTC, weili-govtech approved these changes

2024-04-23 03:03 UTC, merged