CCUBE-1349
LifeSG/web-form-builder pull request #61
Opened 2024-05-29 02:17 UTC by ShIrInRuTh

**Changes**

- Ensured when an element is added the form is in saved state, 
- Amended the code in the basic-details, conditional-rendering, validation & prefill to ensure that it will change the state of the form when input is changed or new entries are added.

**Additional information**

-   You may refer to this [CCUBE-1349](https://jira.ship.gov.sg/browse/CCUBE-1349)

2024-05-29 15:00 UTC, weili-govtech requested changes

2024-05-29 15:00 UTC, weili-govtech commented on src/components/main-panel/main-panel.tsx
> +        focusElement(element, false);
now that there is no need to set the dirty state, we can remove the isDirty argument from `focusElement` and set it as false in the function

2024-05-29 15:00 UTC, weili-govtech commented on src/components/side-panel/side-panel-header.tsx
> +    const isDirty = focusedElement?.isDirty || false;
```suggestion
   const { isDirty } = focusedElement;
```

2024-05-29 15:00 UTC, weili-govtech commented on src/components/side-panel/side-panel-header.tsx
> +                        {isDirty === false ? "Saved" : "Save Changes"}
instead of checking for `false`, check for `falsy` to cover undefined / null values

```suggestion
                        {!isDirty ? "Saved" : "Save Changes"}
```

2024-05-29 15:00 UTC, weili-govtech commented on src/components/element-editor/basic-details/basic-details.tsx
> +        isDirty && Object.keys(touchedFields)?.length > 0;
we shouldnt need `touchedFields`, focused element's dirty state should be dependent on RHF's dirty state only. with this, validation / conditional rendering / prefill wont need to set the dirty state individually

I also notice the form is set as dirty prematurely from the validation / conditional rendering / prefill components, can we avoid that?

2024-06-03 06:46 UTC, ShIrInRuTh commented on src/components/main-panel/main-panel.tsx
> +        focusElement(element, false);
fixed in the last push

2024-06-03 06:46 UTC, ShIrInRuTh commented on src/components/side-panel/side-panel-header.tsx
> +    const isDirty = focusedElement?.isDirty || false;
fixed in the last push

2024-06-03 06:46 UTC, ShIrInRuTh commented on src/components/side-panel/side-panel-header.tsx
> +                        {isDirty === false ? "Saved" : "Save Changes"}
fixed in the last push

2024-06-03 06:46 UTC, ShIrInRuTh commented on src/components/element-editor/basic-details/basic-details.tsx
> +        isDirty && Object.keys(touchedFields)?.length > 0;
fixed in the last push

2024-06-03 13:34 UTC, weili-govtech requested changes

2024-06-03 13:34 UTC, weili-govtech commented on src/context-providers/builder/hook.ts
> +    const focusElement = useCallback((element: TElement, isDirty = false) => {
remove it as I dont see any need to set isDirty anymore
```suggestion
    const focusElement = useCallback((element: TElement) => {
```

2024-06-03 13:34 UTC, weili-govtech commented on src/components/side-panel/side-panel-header.tsx
> +    const isDirty = focusedElement?.isDirty || false;
did you miss pushing this change?

2024-06-03 13:34 UTC, weili-govtech commented on src/components/side-panel/side-panel-header.tsx
> +                        {isDirty === false ? "Saved" : "Save Changes"}
did you miss pushing this change?

2024-06-03 13:34 UTC, weili-govtech commented on src/components/element-editor/basic-details/basic-details.tsx
> +
while this works, it doesnt solve the root cause of the form turning dirty prematurely - the issue is from `Validation`/`ConditionalRendering`/`Prefill` setting the RHF values manually and dirtying it

```js
useEffect(() => {
    setValue("validation", childEntryValues, {
        shouldDirty: true,
    });
}, [childEntryValues]);
```

the issue with RHF values and local states should be solved in https://github.com/LifeSG/web-form-builder/pull/58 so may I request to make sure that PR account for this too

2024-06-05 14:39 UTC, weili-govtech approved these changes

2024-06-05 14:39 UTC, merged