[CCUBE-1353][SR] Adding typing to the function to remove error that is blocking the merging to dev env.
LifeSG/web-form-builder pull request #71
Opened 2024-06-13 02:14 UTC by ShIrInRuTh

**Changes**
- Adding typing to the function to remove error that is blocking the merging to dev env.

2024-06-14 03:02 UTC, weili-govtech requested changes

2024-06-14 03:02 UTC, weili-govtech commented on src/components/common/toast/toasts.tsx
wrap in a fragment instead

```
export const Toasts = () => {
    const { toasts } = useDisplay();

    return (
        <>
            {toasts.map((toast) => (
                <DisplayToast
                    key={toast.id}
                    toast={toast}
                    onClickActionButton={toast.onClickActionButton}
                />
            ))}
        </>
    );
};
```

2024-06-18 01:55 UTC, ShIrInRuTh commented on src/components/common/toast/toasts.tsx
updated in latest changes

2024-06-19 01:34 UTC, weili-govtech approved these changes

2024-06-19 01:34 UTC, merged